# Generated by Django 4.1.6 on 2023-02-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_brand_brand_id_alter_brand_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
